### ISSUE TITLE
`Dynamoid::Adapter.reconnect!` is not thread-safe

### ISSUE THREAD

**Issue by philipmw** [Dynamoid/Dynamoid#10]
A backtrace when a program uses Dynamoid (with AWS SDK v2) in a multi-threaded environment:

     NoMethodError:
       undefined method `list_tables' for nil:NilClass
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter/aws_sdk_v2.rb:220:in `list_tables'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:128:in `list_tables'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:42:in `benchmark'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:128:in `list_tables'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:28:in `reconnect!'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:42:in `benchmark'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:28:in `reconnect!'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:17:in `adapter'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:128:in `get_item'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:42:in `benchmark'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:128:in `get_item'
     # .../dynamoid-1.0.0pre/lib/dynamoid/adapter.rb:80:in `read'

Here's what I think is happening:
  1. Multiple threads simultaneously call `Dynamoid::Adapter.get_item`.
  2. Because Dynamoid isn't connected to a DynamoDB instance yet, multiple threads invoke `Dynamoid::Adapter.reconnect!`. Suppose thread A and B are at the start of `.reconnect!`.
  3. Thread A instantiates an adapter, assigns it to `@adapter`, and calls `@adapter.connect!` (lines 26--27 of adapter.rb). _Context switch to thread B._
  4. Thread B instantiates an adapter, assigns it to `@adapter`, but does not yet call `.connect!`. _Context switch to thread A._
  5. Thread A calls `list_tables` (line 28 of adapter.rb) on an adapter instance that hasn't connected yet.

**Comment by philipmw** [comment]
I have a fix for this; it's on the `prerelease` branch for now because it's based atop of some pending pull requests. I'll post it as a pull request shortly.

**Comment by philipmw** [comment]
Fixed in v1.0.0.
