### ISSUE TITLE
User.find() returns DynamoDB error (The number of conditions on the keys is invalid)

### ISSUE THREAD

**Issue by mightymatth** [Dynamoid/dynamoid#364]
After creating the user, I cannot retrieve it with User.find(). 

Ruby version 2.5.5
Dynamoid version 3.2.0
Running DynamoDB local.

Dynamoid config:

```ruby
require 'dynamoid'

Dynamoid.configure do |config|
  config.region = 'eu-west-1'

  config.namespace = nil
  config.endpoint = 'http://localhost:8000'
end
```

User model:

```ruby
class User
  include Dynamoid::Document

  table name: :users

  range :email
  field :full_name
end
```
Creating the user:

```bash
2.5.5 :028 > u = User.create(email: 'hello')
D, [2019-06-19T17:12:53.158710 #18858] DEBUG -- : put_item | Request "{\"TableName\":\"users\",\"Item\":{\"created_at\":{\"N\":\"1560957173.114342\"},\"updated_at\":{\"N\":\"1560957173.115739\"},\"id\":{\"S\":\"cb974bf0-27ff-472b-b7b2-abd1104533b0\"},\"email\":{\"S\":\"hello\"}},\"Expected\":{\"id\":{\"Exists\":false},\"email\":{\"Exists\":false}}}" | Response "{}"
D, [2019-06-19T17:12:53.159615 #18858] DEBUG -- : (42.27 ms) PUT ITEM - ["users", {:created_at=>0.1560957173114342e10, :updated_at=>0.1560957173115739e10, :id=>"cb974bf0-27ff-472b-b7b2-abd1104533b0", :email=>"hello", :full_name=>nil}, {}]
 => #<User:0x00007fc7d43c23e8 @new_record=false, @attributes={:created_at=>Wed, 19 Jun 2019 17:12:53 +0200, :updated_at=>Wed, 19 Jun 2019 17:12:53 +0200, :id=>"cb974bf0-27ff-472b-b7b2-abd1104533b0", :email=>"hello", :full_name=>nil}, @associations={}, @attributes_before_type_cast={:created_at=>Wed, 19 Jun 2019 17:12:53 +0200, :updated_at=>Wed, 19 Jun 2019 17:12:53 +0200, :id=>"cb974bf0-27ff-472b-b7b2-abd1104533b0", :email=>"hello", :full_name=>nil}, @attributes_changed_by_setter={}, @mutations_from_database=nil, @validation_context=nil, @errors=#<ActiveModel::Errors:0x00007fc7d43ae050 @base=#<User:0x00007fc7d43c23e8 ...>, @messages={}, @details={}>, @previously_changed={}, @mutations_before_last_save=nil> 
```

While finding the user by email works fine:

```bash
2.5.5 :051 > User.where(email: 'hello').first.email
W, [2019-06-19T17:27:07.595056 #18858]  WARN -- : Queries without an index are forced to use scan and are generally much slower than indexed queries!
W, [2019-06-19T17:27:07.595119 #18858]  WARN -- : You can index this query by adding index declaration to user.rb:
W, [2019-06-19T17:27:07.595150 #18858]  WARN -- : * global_secondary_index hash_key: 'some-name', range_key: 'some-another-name'
W, [2019-06-19T17:27:07.595181 #18858]  WARN -- : * local_secondary_index range_key: 'some-name'
W, [2019-06-19T17:27:07.595214 #18858]  WARN -- : Not indexed attributes: :email
D, [2019-06-19T17:27:07.595379 #18858] DEBUG -- : (0.02 ms) SCAN - ["users", {:email=>{:eq=>"hello"}}]
D, [2019-06-19T17:27:07.602412 #18858] DEBUG -- : scan | Request "{\"TableName\":\"users\",\"ScanFilter\":{\"email\":{\"ComparisonOperator\":\"EQ\",\"AttributeValueList\":[{\"S\":\"hello\"}]}}}" | Response "{\"Items\":[{\"created_at\":{\"N\":\"1560957173.114342\"},\"id\":{\"S\":\"cb974bf0-27ff-472b-b7b2-abd1104533b0\"},\"updated_at\":{\"N\":\"1560957173.115739\"},\"email\":{\"S\":\"hello\"}}],\"Count\":1,\"ScannedCount\":2}"
 => "hello" 
```

Retrieving the user by id fails:

```bash
2.5.5 :029 > User.find(u.id)
D, [2019-06-19T17:12:58.305273 #18858] DEBUG -- : get_item | Request "{\"TableName\":\"users\",\"Key\":{\"id\":{\"S\":\"cb974bf0-27ff-472b-b7b2-abd1104533b0\"}}}" | Response "{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"The number of conditions on the keys is invalid\"}"
Traceback (most recent call last):
       16: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/finders.rb:48:in `find'
       15: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/finders.rb:143:in `_find_by_id'
       14: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/adapter.rb:88:in `read'
       13: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/adapter.rb:148:in `block (2 levels) in <class:Adapter>'
       12: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/adapter.rb:54:in `benchmark'
       11: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/adapter.rb:148:in `block (3 levels) in <class:Adapter>'
       10: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/dynamoid-3.2.0/lib/dynamoid/adapter_plugin/aws_sdk_v3.rb:393:in `get_item'
        9: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/client.rb:2601:in `get_item'
        8: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/seahorse/client/request.rb:70:in `send_request'
        7: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/seahorse/client/plugins/response_target.rb:23:in `call'
        6: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        5: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
        4: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
        3: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        2: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-dynamodb-1.30.0/lib/aws-sdk-dynamodb/plugins/simple_attributes.rb:117:in `call'
        1: from /Users/mpevec/.rvm/gems/ruby-2.5.5@attendance-tracker/gems/aws-sdk-core-3.54.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
Aws::DynamoDB::Errors::ValidationException (The number of conditions on the keys is invalid)
```

Is something wrong with User model? Is setup incorrect?

**Comment by est-elle** [comment]
It's because you have a range key (`range: email`) in your model. When you have a composite key, the `find` function expects both of the primary key's components - the hash key and the range key.

Try something like:
`User.find(u.id, range_key: 'hello')`

**Comment by mightymatth** [comment]
Well, it seems I forgot DynamoDB basics... Thanks!
