### ISSUE TITLE
incorrect adapter class name

### ISSUE THREAD

**Issue by jfoo1984** [Dynamoid/dynamoid#497]
I'm seeing this error when trying to create a new document using version 2.2.0 of dynamoid

```
NameError: uninitialized constant Dynamoid::AdapterPlugin::AWSSdkV2
from /var/lib/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
Caused by NameError: uninitialized constant Dynamoid::AdapterPlugin::AWSSdkV2
from /var/lib/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
```

The error appears caused by this line: https://github.com/Dynamoid/dynamoid/blob/a81bf04fe96f6e3113b38fea46136804b646b05e/lib/dynamoid/adapter.rb#L190

because `aws_sdk_v2` is being camel cased to `AWSSdkV2` instead of `AwsSdkV2`, which is the name of the class.

```
[1] pry(main)> Dynamoid::Config.adapter
=> "aws_sdk_v2"
[2] pry(main)> Dynamoid::Config.adapter.camelcase
=> "AWSSdkV2"
```

**Comment by jfoo1984** [comment]
upon further digging, I think this may be due to a locally configured inflection in our project.
